### ISSUE TITLE
Add support for the options trading

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#719]
The Python SDK introduced options trading support in a series of PRs. The .NET SDK should also support this feature. The minimal support level includes:

- [x] The new `option_approved_level` and `option_trading_level ` fields in the account (see [#402](https://github.com/alpacahq/alpaca-py/pull/402) for details)
- [x] The new `max_option_trading_level` field in the account configuration (see [#403](https://github.com/alpacahq/alpaca-py/pull/403) for details)
- [x] The new `us_option` asset type (see [#404](https://github.com/alpacahq/alpaca-py/pull/404) for details) support

This support should be added to the 7.x version of SDK, so it would probably be the 7.1.0 version.
